---
title: Hot Feet
timezone: UTC
collections:
  notes:
    title: Notes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: work
  values:
    excerpt:
    description:
    image:
    client:
    video:
    images:
    - image: 
      caption: 
    discipline: 
    format:
    - 
    screenings:
    - 
    press:
    - publication: 
      link: 
    awards:
    - 
    quotes:
    - quote: 
      cite: 
    layout: page
url: https://www.hotfeet.co
description: We work across borders and cultural divides creating long and short form
  content for online platforms, broadcast and cinematic release.
permalink: pretty
exclude:
- bower.json
- Gemfile.lock
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-paginate-v2
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  auto_ids: false
  input: GFM
  hard_wrap: false
highlighter: rouge
company: Hot Feet Ltd
company-address: Office 5, Unit R1, Penfold Works, Imperial Way, Watford, WD24 4YY
company-registration: '09383714'
colophon: https://www.garethjohnsdesign.com
email: hello@hotfeet.co
analytics: 
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %Y"
future: true
social:
  instagram: https://www.instagram.com/hotfeet/
  facebook: https://www.facebook.com/hotfeet/
  twitter: https://twitter.com/hotfeet
clients:
  bbc: https://www.bbc.co.uk
  conde-nast: https://www.condenast.co.uk
  nike: https://www.nike.com
  refinery-29: https://www.refinery29.com
  the-guardian: https://www.theguardian.com
  the-new-york-times: https://www.nytimes.com
  vice: https://www.vice.com
  youtube: https://www.universalpictures.com
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
pagination:
  collection: posts
  enabled: true
  per_page: 6
  limit: 0
  permalink: "/:num/"
  title: ":title — :num of :max"
  sort_field: date
  sort_reverse: true
autopages:
  enabled: false
imgix:
  source: hotfeet.imgix.net
  secure_url_token: 2K8ntJ8MnNX6Xute
